name: Backport single commit to backport branch

on:
  push:
    branches:
      - main

jobs:
  backport:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to access full commit history

      - name: Fetch backport branch
        run: git fetch origin backport

      - name: Get commit details
        id: commit
        run: |
          COMMIT_SHA=${{ github.sha }}
          IS_MERGE=$(git rev-list --parents -n 1 "$COMMIT_SHA" | wc -w)
          echo "commit_sha=$COMMIT_SHA" >> $GITHUB_OUTPUT
          echo "is_merge=$IS_MERGE" >> $GITHUB_OUTPUT

      - name: Skip merge commits
        if: steps.commit.outputs.is_merge != '2'
        run: echo "✅ Not a merge commit. Proceeding."

      - name: Create Backport PR
        if: steps.commit.outputs.is_merge != '2'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'chore(backport): ${{ steps.commit.outputs.commit_sha }}'
          body: |
            Backport of ${{ steps.commit.outputs.commit_sha }} to `backport` branch.
          base: backport
          head: main
          draft: false
