name: Auto PR from main to backport

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for git log to work properly

      - name: Fetch all branches
        run: git fetch origin backport

      - name: Get non-merge commits between backport and main
        id: commits
        run: |
          COMMITS=$(git log origin/backport..origin/main --no-merges --pretty=format:"%H")
          echo "COMMITS=$COMMITS"
          echo "COMMITS=$COMMITS" >> $GITHUB_OUTPUT

      - name: Check if there are non-merge commits
        id: check
        run: |
          if [ -n "${{ steps.commits.outputs.COMMITS }}" ]; then
            echo "non_merge_commits=true" >> $GITHUB_OUTPUT
          else
            echo "non_merge_commits=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check.outputs.non_merge_commits == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'chore(auto-pr): Sync main to backport'
          body: 'Auto-generated PR to sync direct changes on `main` to `backport`.'
          base: backport
          head: main
          draft: false
