name: Backport direct push to backport

on:
  push:
    branches:
      - main

jobs:
  backport:
    runs-on: ubuntu-latest
    if: github.event.pusher.name != 'web-flow'  # optional extra guard
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if last commit is a merge
        id: check
        run: |
          COMMIT_SHA=${{ github.sha }}
          PARENTS=$(git rev-list --parents -n 1 "$COMMIT_SHA" | wc -w)
          if [ "$PARENTS" -gt 2 ]; then
            echo "This is a merge commit. Skipping."
            echo "is_merge=true" >> $GITHUB_OUTPUT
          else
            echo "This is a direct commit. Continuing."
            echo "is_merge=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Backport PR
        if: steps.check.outputs.is_merge == 'false'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'chore(backport): ${{ github.sha }}'
          body: |
            Backport of direct commit ${{ github.sha }} to `backport` branch.
          base: backport
          head: main
          draft: false
