name: Backport direct commit to backport branch

on:
  push:
    branches:
      - main

jobs:
  backport:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set variables
        id: vars
        run: |
          echo "commit_sha=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Fetch backport branch
        run: git fetch origin backport

      - name: Create new backport branch and cherry-pick
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git checkout -b backport-${{ github.sha }} origin/backport
          git cherry-pick ${{ steps.vars.outputs.commit_sha }} || echo "Nothing to cherry-pick"
        continue-on-error: true

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(backport): cherry-pick ${{ steps.vars.outputs.commit_sha }}"
          title: "chore(backport): cherry-pick ${{ steps.vars.outputs.commit_sha }}"
          body: "Backports ${{ steps.vars.outputs.commit_sha }} to backport branch."
          base: backport
          branch: backport-${{ github.sha }}
